version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
commands:

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/repo
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          command: |
            eb use Udagramapi-env
          name: You may now use the EB CLI within this job
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Backend
          command: |
            npm run backend:deploy
